# Generated by Django 3.0.8 on 2020-08-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
