# Generated by Django 3.0.8 on 2020-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_test',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
