# Generated by Django 3.0.8 on 2020-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200812_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_test',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
