# Generated by Django 3.0.8 on 2020-08-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200802_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group_id',
        ),
    ]
