# Generated by Django 3.0.8 on 2020-08-12 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveIntegerField()),
                ('total_points', models.PositiveIntegerField()),
                ('max_points', models.PositiveIntegerField()),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Topic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
