# Generated by Django 3.0.8 on 2021-02-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='subject',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='tests.Subject'),
            preserve_default=False,
        ),
    ]
