# Generated by Django 3.0.8 on 2021-02-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_testdata_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdata',
            name='subject',
        ),
    ]
