# Generated by Django 3.0.8 on 2021-02-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_testdata_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
