# Generated by Django 3.0.8 on 2021-02-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20210201_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='text',
            new_name='expression',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='pattern',
            name='answer_from',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='answer_to',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='generate_from',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='generate_to',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='question',
            field=models.CharField(default='Что это такое', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='task',
            field=models.TextField(default='Задание'),
            preserve_default=False,
        ),
    ]
