# Generated by Django 3.0.8 on 2021-02-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20210201_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='task',
        ),
    ]
