# Generated by Django 3.0.8 on 2021-02-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_remove_pattern_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='difficulty',
        ),
    ]
