# Generated by Django 3.0.8 on 2021-02-02 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0012_subjectpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectpermission',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Subject'),
        ),
        migrations.AlterField(
            model_name='subjectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
