# Generated by Django 3.2.4 on 2021-06-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20210202_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='chosen_answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.AddField(
            model_name='test',
            name='last_question',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='total_questions',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
