# Generated by Django 3.2.4 on 2021-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20210624_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='last_correct',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='streak',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
