# Generated by Django 3.2.4 on 2021-06-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_auto_20210624_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='last_correct',
        ),
        migrations.AddField(
            model_name='pattern',
            name='difficult',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.IntegerField()),
                ('parent_pattern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.pattern')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='last_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.question'),
        ),
    ]
