# Generated by Django 3.2.4 on 2021-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_auto_20210624_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
