# Generated by Django 3.2.4 on 2021-06-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_auto_20210624_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='heading',
            field=models.CharField(max_length=128),
        ),
    ]
