# Generated by Django 3.2.4 on 2021-06-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_auto_20210624_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='parent_pattern',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.BooleanField(default=False),
        ),
    ]
