# Generated by Django 3.2.4 on 2021-11-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_auto_20210624_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_answer',
            field=models.TextField(default=0),
        ),
    ]
