# Generated by Django 3.2.4 on 2021-11-22 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_auto_20211121_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='questions',
            name='test',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
    ]
