# Generated by Django 3.2.4 on 2021-11-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_auto_20211122_0027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='QuestionsData',
        ),
    ]
