# Generated by Django 3.2.4 on 2021-11-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_questionsdata_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsdata',
            name='user_answer',
            field=models.TextField(default=0),
        ),
    ]
