# Generated by Django 3.2.4 on 2021-11-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_questionsdata_user_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsdata',
            old_name='patterns',
            new_name='pattern',
        ),
        migrations.AddField(
            model_name='question',
            name='pattern',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tests.pattern'),
        ),
    ]
