# Generated by Django 3.2.4 on 2021-11-22 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_auto_20211122_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='questionsdata',
            name='pattern',
        ),
        migrations.AddField(
            model_name='questionsdata',
            name='patterns',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tests.pattern'),
        ),
    ]
