# Generated by Django 3.2.4 on 2021-11-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_auto_20211122_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsdata',
            old_name='patterns',
            new_name='pattern',
        ),
    ]
