# Generated by Django 3.2.4 on 2021-11-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0030_rename_patterns_questionsdata_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pattern',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tests.pattern'),
        ),
    ]
