# Generated by Django 3.2.4 on 2021-11-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_question_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pattern',
        ),
    ]
