# Generated by Django 3.2.4 on 2021-11-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_remove_question_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsdata',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
