# Generated by Django 3.2.4 on 2021-11-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0033_questionsdata_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsdata',
            name='user_answer',
            field=models.IntegerField(default=0),
        ),
    ]
