# Generated by Django 3.2.4 on 2021-11-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0035_questionsdata_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsdata',
            name='max_point',
            field=models.IntegerField(default=0),
        ),
    ]
