# Generated by Django 3.2.4 on 2021-11-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0036_questionsdata_max_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='difficult',
            field=models.IntegerField(choices=[(1, 'Первый уровень'), (2, 'Второй уровень'), (3, 'Третий уровень')], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(),
        ),
    ]
