# Generated by Django 3.2.4 on 2021-11-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0037_auto_20211126_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsdata',
            name='max_point',
        ),
        migrations.AlterField(
            model_name='questionsdata',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
